// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUKu9JIYuTyMZl67AmD3gBevJ-7312yLA',
    appId: '1:74995683070:web:8a7940a0a10fc35ae85faf',
    messagingSenderId: '74995683070',
    projectId: 'planit-e51ad',
    authDomain: 'planit-e51ad.firebaseapp.com',
    storageBucket: 'planit-e51ad.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN1wMY4MlVWIKeuXD7auSIFbAxj5Ey4Mc',
    appId: '1:74995683070:android:b35b618575b9fc7fe85faf',
    messagingSenderId: '74995683070',
    projectId: 'planit-e51ad',
    storageBucket: 'planit-e51ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmFzrp95ca4poMPtoWY3asgtFKonhb8fY',
    appId: '1:74995683070:ios:6e4533f5a4ed33dde85faf',
    messagingSenderId: '74995683070',
    projectId: 'planit-e51ad',
    storageBucket: 'planit-e51ad.firebasestorage.app',
    iosBundleId: 'com.example.planit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmFzrp95ca4poMPtoWY3asgtFKonhb8fY',
    appId: '1:74995683070:ios:6e4533f5a4ed33dde85faf',
    messagingSenderId: '74995683070',
    projectId: 'planit-e51ad',
    storageBucket: 'planit-e51ad.firebasestorage.app',
    iosBundleId: 'com.example.planit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUKu9JIYuTyMZl67AmD3gBevJ-7312yLA',
    appId: '1:74995683070:web:6cb9019999c44826e85faf',
    messagingSenderId: '74995683070',
    projectId: 'planit-e51ad',
    authDomain: 'planit-e51ad.firebaseapp.com',
    storageBucket: 'planit-e51ad.firebasestorage.app',
  );
}
